package shares.gui;

import java.util.ResourceBundle;
import shares.controls.ControlBank;
import shares.controls.ControlBuySell;
import shares.controls.ControlGuiSimulation;
import shares.controls.ControlGuiStart;
import shares.controls.ControlSaveAccount;
import shares.data.Data;
import shares.program.settings.Language;

public class ShareSimulation extends javax.swing.JFrame {
    private static ShareSimulation aShareSimulation;
    
    String baseName = Language.getLanguage();
    ResourceBundle bundle = ResourceBundle.getBundle(baseName);
    
    /**
     * Creates new form ShareSimulation
     */
    private ShareSimulation() {
        initComponents();
        setTitle();
        setLanguage();
        lBankAccValue.setText(ControlBank.getBankAcc());
        lCompanyName.setText(ControlGuiSimulation.getCompanyName());
        lCompanyNameB.setText(ControlGuiSimulation.getCompanyNameB());
        lPortfolioValue.setText(ControlBank.getCurrentPortfolio());
        lCountAValue.setText(ControlGuiSimulation.getHoldShareA());
        lCountBValue.setText(ControlGuiSimulation.getHoldShareB());
        lShowRate.setText(ControlBank.getCurrentShareARate());
        lShowRateB.setText(ControlBank.getCurrentShareBRate());
        lNotice.setVisible(false);
        mFile.setText(bundle.getString("mFile"));
        mFileExit.setText(bundle.getString("mFileExit"));
        lSavAccValue.setText(ControlSaveAccount.getSaveAccountValue());
        lInterestValue.setText(ControlSaveAccount.getInterestProcent());
        
        //set rbtn-text
        rbtnA.setText(Data.getCompanyName());
        rbtnB.setText(Data.getCompanyNameB());
        
        //select one radioButton and list entry
        rbtnA.setSelected(true);
        listCount.setSelectedIndex(0);
        listSaveAccount.setSelectedIndex(0);
              
        //buttonGroup
        buttonGroup1.add(rbtnA);
        buttonGroup1.add(rbtnB);
        
        //hide
        btnEndGame.setVisible(false);
        
    }
    
    static public ShareSimulation getInstance(){
        if(aShareSimulation == null){
            aShareSimulation = new ShareSimulation();
        }
        return aShareSimulation;
    }
    
    private void setLanguage(){
        baseName= Language.getLanguage();
        bundle = ResourceBundle.getBundle(baseName);
        
        setTitle();
        
        lBankAcc.setText(bundle.getString("lBankAcc"));
        lPortfolio.setText(bundle.getString("lPortfolio"));
        lRate.setText(bundle.getString("lRate"));
        lSpecific.setText(bundle.getString("lSpecific"));
        lCountA.setText(bundle.getString("lCountA"));
        btnNextRound.setText(bundle.getString("btnNextRound"));
        btnSell.setText(bundle.getString("btnSell"));
        btnBuy.setText(bundle.getString("btnBuy"));
        btnAbort.setText(bundle.getString("btnAbort"));
        btnEndGame.setText(bundle.getString("btnExit"));
        btnPayIn.setText(bundle.getString("btnPayIn"));
        btnPayOut.setText(bundle.getString("btnPayOut"));
        lInterestR.setText(bundle.getString("lInterestR"));
        lSaveAccount.setText(bundle.getString("lSaveAccount"));
        btnSim30Days.setText(bundle.getString("btnSim30Days"));
                
        //menu
        mFile.setText(bundle.getString("mFile"));
        mFileExit.setText(bundle.getString("mFileExit"));
        mFileNewGame.setText(bundle.getString("mFileNewGame"));
        mOptions.setText(bundle.getString("mOptions"));
        mOptionsLanguageEn.setText(bundle.getString("mOptionsLanguageEn"));
        mOptionsLanguageDe.setText(bundle.getString("mOptionsLanguageDe"));
        mFileNewPlayer.setText(bundle.getString("mFileNewPlayer"));
        
                
    }
    
    public void refreshData(){
        lBankAccValue.setText(ControlBank.getBankAcc());
        lPortfolioValue.setText(ControlBank.getCurrentPortfolio());
        lCountAValue.setText(ControlGuiSimulation.getHoldShareA());
        lShowRate.setText(ControlBank.getCurrentShareARate());
        lShowRateB.setText(ControlBank.getCurrentShareBRate());
        lCountBValue.setText(ControlGuiSimulation.getHoldShareB());
        lSavAccValue.setText(ControlSaveAccount.getSaveAccountValue());
        lInterestValue.setText(ControlSaveAccount.getInterestProcent());
        setTitle();
                
    }
    
    private void setTitle(){
        this.setTitle(bundle.getString("title") + "             " + Data.getAPlayer().getNickname().toUpperCase()  
                + ":      "+ControlGuiSimulation.getCurrentDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnNextRound = new javax.swing.JButton();
        lBankAcc = new javax.swing.JLabel();
        lPortfolio = new javax.swing.JLabel();
        lBankAccValue = new javax.swing.JLabel();
        lPortfolioValue = new javax.swing.JLabel();
        lCompanyName = new javax.swing.JLabel();
        lRate = new javax.swing.JLabel();
        lShowRate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lSpecific = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSell = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCount = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        btnAbort = new javax.swing.JButton();
        lCountA = new javax.swing.JLabel();
        lCountAValue = new javax.swing.JLabel();
        btnEndGame = new javax.swing.JButton();
        lNotice = new javax.swing.JLabel();
        lCompanyNameB = new javax.swing.JLabel();
        lShowRateB = new javax.swing.JLabel();
        lCountBValue = new javax.swing.JLabel();
        rbtnA = new javax.swing.JRadioButton();
        rbtnB = new javax.swing.JRadioButton();
        lSaveAccount = new javax.swing.JLabel();
        lSavAccValue = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSaveAccount = new javax.swing.JList<>();
        btnPayIn = new javax.swing.JButton();
        btnPayOut = new javax.swing.JButton();
        lInterestR = new javax.swing.JLabel();
        lInterestValue = new javax.swing.JLabel();
        btnSim30Days = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mFileNewGame = new javax.swing.JMenuItem();
        mFileNewPlayer = new javax.swing.JMenuItem();
        mFileExit = new javax.swing.JMenuItem();
        mOptions = new javax.swing.JMenu();
        mOptionsLanguageEn = new javax.swing.JMenuItem();
        mOptionsLanguageDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        btnNextRound.setBackground(new java.awt.Color(255, 255, 153));
        btnNextRound.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNextRound.setForeground(new java.awt.Color(0, 102, 255));
        btnNextRound.setText("btnNextRound");
        btnNextRound.setMaximumSize(new java.awt.Dimension(105, 23));
        btnNextRound.setMinimumSize(new java.awt.Dimension(105, 23));
        btnNextRound.setPreferredSize(new java.awt.Dimension(105, 23));
        btnNextRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextRoundActionPerformed(evt);
            }
        });

        lBankAcc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lBankAcc.setForeground(new java.awt.Color(0, 102, 255));
        lBankAcc.setText("Bank Account:");

        lPortfolio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lPortfolio.setForeground(new java.awt.Color(0, 102, 255));
        lPortfolio.setText("Portfolio:");

        lBankAccValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lBankAccValue.setForeground(new java.awt.Color(0, 102, 255));
        lBankAccValue.setText("5000,00 €");

        lPortfolioValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lPortfolioValue.setForeground(new java.awt.Color(0, 102, 255));
        lPortfolioValue.setText("1500,00 €");

        lCompanyName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lCompanyName.setForeground(new java.awt.Color(0, 102, 255));
        lCompanyName.setText("CompanyName");

        lRate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lRate.setForeground(new java.awt.Color(0, 102, 255));
        lRate.setText("Rate:");

        lShowRate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lShowRate.setForeground(new java.awt.Color(0, 102, 255));
        lShowRate.setText("85,36 €");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        lSpecific.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lSpecific.setForeground(new java.awt.Color(0, 102, 255));
        lSpecific.setText("specific quantity");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btnSell.setBackground(new java.awt.Color(255, 153, 153));
        btnSell.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSell.setForeground(new java.awt.Color(0, 102, 255));
        btnSell.setText("Sell");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        btnBuy.setBackground(new java.awt.Color(153, 255, 153));
        btnBuy.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(0, 102, 255));
        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        listCount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        listCount.setForeground(new java.awt.Color(0, 102, 255));
        listCount.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "5", "10", "15", "20", "25", "30", "50", "70", "100" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCount.setSelectionForeground(new java.awt.Color(0, 102, 204));
        jScrollPane1.setViewportView(listCount);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        btnAbort.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAbort.setForeground(new java.awt.Color(0, 102, 255));
        btnAbort.setText("btnAbort");
        btnAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbortActionPerformed(evt);
            }
        });

        lCountA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lCountA.setForeground(new java.awt.Color(0, 102, 255));
        lCountA.setText("lCountA:");

        lCountAValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lCountAValue.setForeground(new java.awt.Color(0, 102, 255));
        lCountAValue.setText("lCountAValue");

        btnEndGame.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEndGame.setForeground(new java.awt.Color(0, 102, 255));
        btnEndGame.setText("btnEndGame");
        btnEndGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndGameActionPerformed(evt);
            }
        });

        lNotice.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lNotice.setForeground(new java.awt.Color(153, 0, 0));
        lNotice.setText("lNotice");

        lCompanyNameB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lCompanyNameB.setForeground(new java.awt.Color(0, 102, 255));
        lCompanyNameB.setText("lCompanyNameB");

        lShowRateB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lShowRateB.setForeground(new java.awt.Color(0, 102, 255));
        lShowRateB.setText("lShowRateB");

        lCountBValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lCountBValue.setForeground(new java.awt.Color(0, 102, 255));
        lCountBValue.setText("lCountBValue");

        rbtnA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbtnA.setForeground(new java.awt.Color(0, 102, 255));
        rbtnA.setText("Share A");

        rbtnB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbtnB.setForeground(new java.awt.Color(0, 102, 255));
        rbtnB.setText("Share B");

        lSaveAccount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lSaveAccount.setForeground(new java.awt.Color(0, 102, 255));
        lSaveAccount.setText("lSaveAccount");

        lSavAccValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lSavAccValue.setForeground(new java.awt.Color(0, 102, 255));
        lSavAccValue.setText("lSavAccValue");

        listSaveAccount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        listSaveAccount.setForeground(new java.awt.Color(0, 102, 255));
        listSaveAccount.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "50", "100", "200", "500", "1000" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSaveAccount.setSelectionForeground(new java.awt.Color(0, 102, 255));
        jScrollPane2.setViewportView(listSaveAccount);

        btnPayIn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPayIn.setForeground(new java.awt.Color(0, 102, 255));
        btnPayIn.setText("btnPayIn");
        btnPayIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayInActionPerformed(evt);
            }
        });

        btnPayOut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPayOut.setForeground(new java.awt.Color(0, 102, 255));
        btnPayOut.setText("btnPayOut");
        btnPayOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayOutActionPerformed(evt);
            }
        });

        lInterestR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lInterestR.setForeground(new java.awt.Color(0, 102, 204));
        lInterestR.setText("lInterestR");

        lInterestValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lInterestValue.setForeground(new java.awt.Color(0, 102, 204));
        lInterestValue.setText("lInterestValue");

        btnSim30Days.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSim30Days.setForeground(new java.awt.Color(0, 102, 204));
        btnSim30Days.setText("btnSim30Days");
        btnSim30Days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSim30DaysActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        mFile.setText("File");

        mFileNewGame.setText("mFileNewGame");
        mFileNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFileNewGameActionPerformed(evt);
            }
        });
        mFile.add(mFileNewGame);

        mFileNewPlayer.setText("mFileNewPlayer");
        mFileNewPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFileNewPlayerActionPerformed(evt);
            }
        });
        mFile.add(mFileNewPlayer);

        mFileExit.setText("jMenuItem1-Exit");
        mFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFileExitActionPerformed(evt);
            }
        });
        mFile.add(mFileExit);

        jMenuBar1.add(mFile);

        mOptions.setText("mOptions");

        mOptionsLanguageEn.setText("mOptionsLanguageEn");
        mOptionsLanguageEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOptionsLanguageEnActionPerformed(evt);
            }
        });
        mOptions.add(mOptionsLanguageEn);

        mOptionsLanguageDe.setText("mOptionsLanguageDe");
        mOptionsLanguageDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOptionsLanguageDeActionPerformed(evt);
            }
        });
        mOptions.add(mOptionsLanguageDe);

        jMenuBar1.add(mOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lBankAcc)
                                    .addComponent(lPortfolio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lBankAccValue)
                                    .addComponent(lPortfolioValue)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnA)
                                    .addComponent(rbtnB))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lCompanyName)
                                                        .addGap(109, 109, 109))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lCountA)
                                                            .addComponent(lRate))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lShowRate)
                                                            .addComponent(lCountAValue))))
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lShowRateB)
                                                    .addComponent(lCompanyNameB)
                                                    .addComponent(lCountBValue))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(452, 452, 452))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lSaveAccount)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lInterestR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lInterestValue))
                                    .addComponent(lSavAccValue)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnPayIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPayOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAbort, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnSim30Days, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(btnNextRound, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNotice, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lSpecific)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBankAcc)
                    .addComponent(lBankAccValue)
                    .addComponent(lCompanyName)
                    .addComponent(lCompanyNameB))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPortfolio)
                    .addComponent(lPortfolioValue)
                    .addComponent(lRate)
                    .addComponent(lShowRate)
                    .addComponent(lShowRateB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCountA)
                    .addComponent(lCountAValue)
                    .addComponent(lCountBValue))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lSpecific)
                            .addComponent(lSaveAccount)
                            .addComponent(lSavAccValue))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtnA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtnB))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(124, 124, 124)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lInterestR)
                                    .addComponent(lInterestValue))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAbort, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPayIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNextRound, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPayOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSim30Days, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNotice)
                .addGap(59, 59, 59))
        );

        setBounds(0, 0, 629, 497);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        int share = -1;
        if(rbtnA.isSelected()){
            share = 0;
        }
        else share = 1;
        boolean ok = ControlBuySell.processBuyOrder(listCount.getSelectedValue(), share);
        
        if(!ok){
            lNotice.setText(bundle.getString("ErrorTooMuchShares"));
            lNotice.setVisible(true);
        }
        
        //if transaction is fine, than refresh all data
        refreshData();
        if(ok)
            lNotice.setVisible(false);
        
        
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        
        int share = -1;
        if(rbtnA.isSelected()){
            share = 0;
        }
        else share = 1;
        boolean ok = ControlBuySell.processSellOrder(listCount.getSelectedValue(), share);
        
        if(!ok){
            lNotice.setText(bundle.getString("ErrorHolding"));
            lNotice.setVisible(true);
        }
        
        //refresh data, if transaction is done
        refreshData();
        if(ok)
            lNotice.setVisible(false);
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnNextRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextRoundActionPerformed
        ControlGuiSimulation.newRound();
        refreshData();
    }//GEN-LAST:event_btnNextRoundActionPerformed

    private void btnAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbortActionPerformed
        Score score = new Score();
        score.setLocationRelativeTo(null);
        score.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAbortActionPerformed

    private void mFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFileExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_mFileExitActionPerformed

    private void btnEndGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndGameActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnEndGameActionPerformed

    private void btnPayInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayInActionPerformed
        
       boolean ok = ControlSaveAccount.processAddAmountToSaveAcc(listSaveAccount.getSelectedValue());
       
       if(!ok){
           lNotice.setText(bundle.getString("ErrorTooMuchShares"));
           lNotice.setVisible(true);
       }
       //refresh data, if transaction is done
        refreshData();
        if(ok)
            lNotice.setVisible(false);       
        
        
    }//GEN-LAST:event_btnPayInActionPerformed

    private void btnPayOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayOutActionPerformed
        
        boolean ok = ControlSaveAccount.processRemovefromSaveAcc(listSaveAccount.getSelectedValue());
        
        if(!ok){
           lNotice.setText(bundle.getString("ErrorSaveAcc"));
           lNotice.setVisible(true);
       }
       //refresh data, if transaction is done
        refreshData();
        if(ok)
            lNotice.setVisible(false);
        
    }//GEN-LAST:event_btnPayOutActionPerformed

    private void mFileNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFileNewGameActionPerformed
        ControlGuiSimulation.startNewGame();
        refreshData();
    }//GEN-LAST:event_mFileNewGameActionPerformed

    private void mOptionsLanguageEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOptionsLanguageEnActionPerformed
        Language.setLanguage(Language.aLanguage.ENGLISH);
        setLanguage();
    }//GEN-LAST:event_mOptionsLanguageEnActionPerformed

    private void mOptionsLanguageDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOptionsLanguageDeActionPerformed
        Language.setLanguage(Language.aLanguage.GERMAN);
        setLanguage();
    }//GEN-LAST:event_mOptionsLanguageDeActionPerformed

    private void btnSim30DaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSim30DaysActionPerformed
        ControlGuiSimulation.new30rounds();
        refreshData();
    }//GEN-LAST:event_btnSim30DaysActionPerformed

    private void mFileNewPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFileNewPlayerActionPerformed
       ControlGuiStart.startWithNewPlayer();
    }//GEN-LAST:event_mFileNewPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShareSimulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbort;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnEndGame;
    private javax.swing.JButton btnNextRound;
    private javax.swing.JButton btnPayIn;
    private javax.swing.JButton btnPayOut;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnSim30Days;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lBankAcc;
    private javax.swing.JLabel lBankAccValue;
    private javax.swing.JLabel lCompanyName;
    private javax.swing.JLabel lCompanyNameB;
    private javax.swing.JLabel lCountA;
    private javax.swing.JLabel lCountAValue;
    private javax.swing.JLabel lCountBValue;
    private javax.swing.JLabel lInterestR;
    private javax.swing.JLabel lInterestValue;
    private javax.swing.JLabel lNotice;
    private javax.swing.JLabel lPortfolio;
    private javax.swing.JLabel lPortfolioValue;
    private javax.swing.JLabel lRate;
    private javax.swing.JLabel lSavAccValue;
    private javax.swing.JLabel lSaveAccount;
    private javax.swing.JLabel lShowRate;
    private javax.swing.JLabel lShowRateB;
    private javax.swing.JLabel lSpecific;
    private javax.swing.JList<String> listCount;
    private javax.swing.JList<String> listSaveAccount;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem mFileExit;
    private javax.swing.JMenuItem mFileNewGame;
    private javax.swing.JMenuItem mFileNewPlayer;
    private javax.swing.JMenu mOptions;
    private javax.swing.JMenuItem mOptionsLanguageDe;
    private javax.swing.JMenuItem mOptionsLanguageEn;
    private javax.swing.JRadioButton rbtnA;
    private javax.swing.JRadioButton rbtnB;
    // End of variables declaration//GEN-END:variables
}
